kind: pipeline
type: docker
name: drone-test

steps:
- name: main-push-step_1
  image: alpine
  commands:
  - echo hello
  - echo main-push_1
  when:
    branch:
      include:
      - main
    event:
      include:
      - push

- name: main-push-step_2
  image: alpine
  commands:
  - echo world
  - echo main-push_2
  when:
    branch:
      include:
      - main
    event:
      include:
      - push

- name: main-push-step_final
  image: alpine
  commands:
  - echo main-push-step_final
  depends_on:
  - main-push-step_1
  - main-push-step_2
  when:
    branch:
      include:
      - main
    event:
      include:
      - push

- name: dev-push
  image: alpine
  commands:
  - echo hello world
  - echo dev-push
  when:
    branch:
      include:
      - dev
    event:
      include:
      - push

- name: cron_job
  image: alpine
  commands:
  - echo run cron job
  when:
    event:
    - cron:
    cron:
      include:
      - every2hour

---
kind: pipeline
type: ssh
name: default

server:
  host:
    from_secret: GCP_IP_HOST
  user:
    from_secret: USER_NAME
  ssh_key:
    from_secret: USER_PRIVATE_SSH_KEY

steps:
  - name: greeting
    commands:
      - echo hello world
      - whoami
      - cd /User/project_path
      - pwd
