version: '3'

services:
  nodejs:
    container_name: docker_prerender
    build:
      context: ./
      shm_size: '2gb'
      dockerfile: ./nodejs/Dockerfile
    environment:
      - CACHE_MAXSIZE=1000
      - CACHE_TTL=600
    restart: always
    ports:
      - "3000:3000"
