version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    ports: 
      - "8080:8080"
      - "50000:50000"
    volumes: 
     - ./jenkins_data:/var/jenkins_home
    restart: always
